[package]
name = "practice_Rust"
version = "0.1.0"
edition = "2021"

[dependencies]

[[bin]]
name = "day1_hello"
path = "entry/week1/day1_hello.rs"

[[bin]]
name = "day1_class"
path = "entry/week1/day1_class.rs"

[[bin]]
name = "day1_vals"
path = "entry/week1/day1_vals.rs"

[[bin]]
name = "day1_sha"
path = "entry/week1/day1_sha.rs"

[[bin]]
name = "day2_if"
path = "entry/week1/day2_if.rs"

[[bin]]
name = "day2_if_a"
path = "entry/week1/day2_if_a.rs"

[[bin]]
name = "day3_match"
path = "entry/week1/day3_match.rs"

[[bin]]
name = "day4_loop"
path = "entry/week1/day4_loop.rs"

[[bin]]
name = "day5_owner"
path = "entry/week1/day5_owner.rs"


[[bin]]
name = "day6_borrowing"
path = "entry/week1/day6_borrowing.rs"

[[bin]]
name = "day7_slice"
path = "entry/week1/day7_slice.rs"
